version: '3'

services:

  go-frontend:
    image: ghcr.io/wuldnarp/simple-fortune-cookie-frontend-app:1.0-176a2eb4
    depends_on:
      - go-backend
    ports:
      - 8080:8080
    links:
      - go-backend
    environment:
      - BACKEND_DNS=go-backend

  go-backend:
    image: ghcr.io/wuldnarp/simple-fortune-cookie-backend-app:1.0-176a2eb4
    restart: always

