apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - image: ghcr.io/wuldnarp/simple-fortune-cookie-backend-app:1.0-1a62f8b8
          name: simple-fortune-cookie-backend-app
          ports:
            - containerPort: 9000
          