name: pipeline
on:
    pull_request:
        types:
            - closed

env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Docker-image-backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: build docker
      run: cd ./backend && chmod +x ../ci/backend-build-docker.sh && ../ci/backend-build-docker.sh
    - name: push docker
      run: cd ./backend && chmod +x ../ci/backend-push-docker.sh && ../ci/backend-push-docker.sh

  Docker-image-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: build docker
      run: cd ./frontend && chmod +x ../ci/frontend-build-docker.sh && ../ci/frontend-build-docker.sh
    - name: push docker
      run: cd ./frontend && chmod +x ../ci/frontend-push-docker.sh && ../ci/frontend-push-docker.sh
      