name: hello-world
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - name: download code
        uses: actions/checkout@v3

      - name: ls
        run: ls --all

      - name: build backend
        run:  cd backend | go build

      - name: build frontend
        run: cd frontend | go build

      - name: create artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  Tests:
    runs-on: ubuntu-latest
    container: golang:1.16
    needs: [Build]
    steps:
      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: run tests
        run: go test ./...

