name: hello-world
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Go backend tests
        run: go test -v ./backend
        
      - name: Go frontejd tests
        run: go test -v ./frontend
