name: hello-world
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - name: download code
        uses: actions/checkout@v3

      - name: build backend
        run: go build ./backend

      - name: build frontend
        run: go build ./frontend

      - name: create artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  Tests:
    runs-on: ubuntu-latest
    container: golang:1.16
    needs: [Build]
    steps:
      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: run tests
        run: go test ./...

