name: pipeline
on: push

jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: test backend
        run:  cd ./backend && go test
      - name: test frontend
        run: cd ./frontend && go test

  Build:
    runs-on: ubuntu-latest
    container: golang:1.16
    needs: [Unit-tests]
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: build backend
        run:  cd ./backend && go build
      - name: build frontend
        run: cd ./frontend && go build
      - name: create artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .