name: hello-world
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Go backend tests
        run: go test -v ./backend
      - name: Go frontejd tests
        run: go test -v ./frontend
